name: tcp_scanner
description: Simple and fast TCP scanner.
version: 2.0.2
homepage: https://github.com/shpak86/tcp_scanner

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
